### ISSUE TITLE
不能设置值

### ISSUE THREAD

**Issue by huayicheng2015** [lovely3x/WeightAndHeightMeasurer#1]

**Comment by lovely3x** [comment]
这个是利用滚动来设置指定的位置的，所以需要在能够获取到控件高度时调用。
你可以尝试用下面的方式来设置
        hvMeasurer.getViewTreeObserver().addOnGlobalLayoutListener(new ViewTreeObserver.OnGlobalLayoutListener() {
            @Override
            public void onGlobalLayout() {
                hvMeasurer.getViewTreeObserver().removeGlobalOnLayoutListener(this);
                hvMeasurer.setCurrentLine(bodyWeight);
            }
        });
