### ISSUE TITLE
如果不是从0开始绘制，则显示有点问题，并且怎么才能默认选中想要的数值？

### ISSUE THREAD

**Issue by zcbin88** [lovely3x/WeightAndHeightMeasurer#3]
如果mStartLine = 15 则刚打开界面的时候就会出现显示不完整的问题，这个问题怎么解决啊？并且怎么才能默认选中想要的值？谢谢

**Comment by lovely3x** [comment]
mStartLine 要为10的倍数。
像这样setCurrentLine就可以选中默认值。
![image](https://cloud.githubusercontent.com/assets/7817253/24150975/63c23bf2-0e82-11e7-959b-73bbdff9fd6f.png)

**Comment by lovely3x** [comment]
刚刚我抽空修改了源代码，已经支持任意起始值的设置了。

**Comment by zcbin88** [comment]
问题解决了，谢谢大神
